### ISSUE TITLE
Password managers fall for honeypot field in registration/login forms

### ISSUE THREAD

**Issue by mivanov** [localwiki/localwiki#169]
I was able to reproduce this using the LastPass password manager.  Can also happen with Chrome though, and probably any password manager that just uses the position of the field or just tries too hard.  Not specific to django-honeypot or LastPass.  See http://www.alexanderinteractive.com/blog/2011/02/chrome%E2%80%99s-autofill-and-honeypot-fields/ for example.

**Comment by BenLewies** [comment]
I would strongly advise against any approach that interferes with the functioning of a user's password manager.

I believe that the honeypot approach has perhaps outlived its usefulness and that there are more effective and user friendly solutions out there.

Please take a look at the new reCaptcha - https://www.google.com/recaptcha/intro/

It is user friendly and quick to use.  Why not just do away with honeypots altogether and put a reCaptcha as a standard bot-prevention mechanism on your login form?
