### ISSUE TITLE
schema.org schema

### ISSUE THREAD

**Issue by philipn** [localwiki/localwiki#30]
For places, at least.  And map pages.

It's based on HTML5 microdata.

Just look into this.  May not be best choice.  RDFa?  Other things?  This seems like a contentious proposal in the OSS community / microformats / semantic  -- totally top-down.

**Comment by samrose** [comment]
(Most of) the world arrived at schema.org. schema.org now totally supports RDF/OWL/RDFa 

LocalWiki could really benefit from structured and open-standards based/interoperable data
