### ISSUE TITLE
Versioning of previously unversioned model with FK doesn't work

### ISSUE THREAD

**Issue by mivanov** [localwiki/localwiki#369]
Right now versioning with FK's only works for objects created after versioning was enabled. If there are objects that were created before versioning was enabled (i.e. they have no history), when creating a historical record for a model that has the FK, their historical id will not be found , and the FK will be set to None, which may not be allowed.

Propose adding a management command or hook into syncdb to create a historical record for all versioned objects that don't have one yet (or just the ones that just started to be versioned). Either that or fixing the handling of FK's to avoid this issue.

Minor thing, but stumped me for a few.

**Comment by philipn** [comment]
This issue was moved to localwiki/localwiki-backend-server#61
