### ISSUE TITLE
Headings Dont Wrap with Images and Maps Properly

### ISSUE THREAD

**Issue by ndstate** [localwiki/localwiki#433]
Text formatted as a heading does not wrap properly with images and maps that are aligned to say the right or left.  The text will automatically render below the end of the image or map.  

See http://twincitieswiki.org/Test_Page for an example of an image doing this and https://scruzwiki.org/Royal_Oaks for a map doing this.

Thanks.

**Comment by philipn** [comment]
This issue was moved to localwiki/localwiki-backend-server#42
