### ISSUE TITLE
Map error: too few points in geometry component.

### ISSUE THREAD

**Issue by vielmetti** [localwiki/localwiki#496]
Here's the associated textarea:

<textarea id="id_geom_geom" rows="10" cols="40" name="geom">SRID=4326;GEOMETRYCOLLECTION (LINESTRING (-83.7005566606293883 42.2575130479860235, -83.7005566606293883 42.2575130479860235), LINESTRING (-83.6926602372892887 42.2584024038051922, -83.6832188615572221 42.2293012569692294, -83.7094830522300697 42.2087063131416826, -83.6907719621432875 42.1742392616933088, -83.6952351579439124 42.1519719538693209, -83.6804722795266827 42.1291875718467494), LINESTRING (-83.6964367875820443 42.1240949691253732, -83.6964367875820443 42.1240949691253732), LINESTRING (-83.7007283220062703 42.1235856863376981, -83.6991833696138912 42.0927664620622011, -83.6984967241056808 42.0591284027497636), LINESTRING (-83.6952351579440972 42.0623145892688655, -83.6952351579440972 42.0623145892688655), LINESTRING (-83.6830472001806243 42.0556871417382112, -83.6839055070654325 42.0102960402295977, -83.6971234330902831 41.9919263872112296))</textarea>

**Comment by philipn** [comment]
This issue was moved to localwiki/localwiki-backend-server#36
