### ISSUE TITLE
Maps Do Not Handle Pages With / In Them Correctly

### ISSUE THREAD

**Issue by ndstate** [localwiki/localwiki#505]
If a page that has a / in it is mapped it does not link properly from the map.

To reproduce the error go to http://twincitieswiki.org/map/#zoom=15&lat=45.011&lon=-93.25524&layers=BTT and click on the big area in the middle of the map.  Along the left side you will find a link to that area, called Minneapolis/Holland -- if you click on this it does not redirect you to the correct location. %2F is not equaling / 

You will note that http://twincitieswiki.org/map/Minneapolis/Holland is working correctly.

Thanks

**Comment by philipn** [comment]
This issue was moved to localwiki/localwiki-backend-server#34
