### ISSUE TITLE
Spell checker in Firefox is overiden by editor's copy/paste

### ISSUE THREAD

**Issue by moorepants** [localwiki/localwiki#608]
If I'm editing a page in Firefox in the WYSIWYG editor and I have a spelling mistake, Firefox underlines the misspelled word in a squiggle red line. I typically right click the word and select the correct word but this is not possible in the editor in localwiki, I simply get a menu with a custom copy and/or paste button.

**Comment by philipn** [comment]
This issue was moved to localwiki/localwiki-backend-server#25
