### ISSUE TITLE
Maps: Zoom keys work while using search + problems with non-qwerty keyboard layouts

### ISSUE THREAD

**Issue by hng** [localwiki/localwiki#667]
While typing in the search field inside the ("edit") map keys that are used for zooming (+, -) still zoom the map and don't show up in the search field. This is a problem in connection with another bug: on non-qwerty keyboard layouts not only do the "+" and "-" keys zoom the map, but also the keys that are the "+" and "-" keys on the qwerty-keyboard. E.g. with a German keyboard layout the keys "ß" and "´" zoom the map and can't be used in the search field ("Straße").

**solution**
This looks like a similar problem with an easy solution: https://github.com/lonvia/waymarked-trails-site/issues/54 and the commit https://github.com/lonvia/waymarked-trails-site/commit/58fb12eacf398a228f1de0fe9a8bdc3e3484dc57
(I would have tested and fixed it myself, but so far I haven't managed to get the localwiki source code to run)

**Comment by philipn** [comment]
This issue was moved to localwiki/localwiki-backend-server#20
