### ISSUE TITLE
Signup form errors are visually confusing

### ISSUE THREAD

**Issue by hampelm** [localwiki/localwiki#685]
If you try to sign up but there is a validation error, you get error messages. However, the messages aren't visually associated with the fields, so users don't understand what the errors refer to. 

In the example below, the first error looks like it isn't associated with any field and the second error is associated with the "Name" field, even though it refers to the email field. This confused a user and prevented them from signing up: 

![2014-02-22 11 31 16 am](https://f.cloud.github.com/assets/86435/2238147/1c44af26-9bdf-11e3-9781-ff19420889dd.png)

**Comment by philipn** [comment]
This issue was moved to localwiki/localwiki-backend-server#15
