### ISSUE TITLE
bug: "Add page" button doesn't work if used from a diff

### ISSUE THREAD

**Issue by mk30** [localwiki/localwiki#706]
couple examples:

http://localwiki.net/sf/Clean_up_the_Plaza/_history/2014-07-23%2019:25:53.075413...#
http://localwiki.net/ann-arbor/Tutoring/_history/2014-07-24%2011:00:40.822348...#

**Comment by philipn** [comment]
This issue was moved to localwiki/localwiki-backend-server#10
