### ISSUE TITLE
Provide data dumps

### ISSUE THREAD

**Issue by nemobis** [localwiki/localwiki#713]
Hello, I'm from WikiTeam and we love regiowikis since forever, see https://en.wikipedia.org/wiki/User:Emijrp/Regiowikis

It would be wonderful if you could provide public data dump for "portability" of your free content, similar to dumps.wikimedia.org. We'd also be glad to mirror them on archive.org for you (but you could also upload them there yourself).

**Comment by philipn** [comment]
Closing this, as we won't be doing this for now.  Please use the API, which contains all information stored in the database (sans private user information).

See also https://github.com/localwiki/localwiki/issues/584

**Comment by ghost** [comment]
please reconsider this as not everyone has unlimited internet access

**Comment by hampelm** [comment]
@dclbndyf Do you have a particular use case or format in mind? It should be possible to make an archiver or exporter that uses the API to export a certain region for offline use.

**Comment by ghost** [comment]
see #763 
I believe they use the zim format.
