### ISSUE TITLE
Very long page names result in memcached error

### ISSUE THREAD

**Issue by vielmetti** [localwiki/localwiki#717]
See https://app.getsentry.com/localwikiorg/localwiki/group/30446662/

Repeat by viewing a page with a crazy long URL, like this nonsense.

http://localwiki.net/humboldt/64%20bytes%20from%208.8.8.8:%20icmp_seq=24620%20ttl=46%20time=40.590%20ms%2064%20bytes%20from%208.8.8.8:%20icmp_seq=24621%20ttl=46%20time=40.144%20ms%2064%20bytes%20from%208.8.8.8:%20icmp_seq=24622%20ttl=46%20time=40.039%20ms%2064%20bytes%20from%208.8.8.8:%20icmp_seq=24623%20ttl=46%20time=40.179%20ms%2064%20bytes%20from%208.8.8.8:%20icmp_seq=24624%20ttl=46%20time=39.913%20ms%2064%20bytes%20from%208.8.8.8:%20icmp_seq=24625%20ttl=46%20time=40.954%20ms%2064%20bytes%20from%208.8.8.8:%20icmp_seq=24626%20ttl=46%20time=47.636%20ms%2064%20bytes%20from%208.8.8.8:%20icmp_seq=24627%20ttl=46%20time=40.674%20ms%2064%20bytes%20from%208.8.8.8:%20icmp_seq=24628%20ttl=46%20time=40.367%20ms%2064%20bytes%20from%208.8.8.8:%20icmp_seq=24629%20ttl=46%20time=40.126%20ms%2064%20bytes%20from%208.8.8.8:%20icmp_seq=24630%20ttl=46%20time=44.439%20ms%2064%20bytes%20from%208.8.8.8:%20icmp_seq=24631%20ttl=46%20time=40.263%20ms%2064%20bytes%20from%208.8.8.8:%20icmp_seq=24632%20ttl=46%20time=40.539%20ms%2064%20bytes%20from%208.8.8.8:%20icmp_seq=24633%20ttl=46%20time=40.972%20ms

The error is 

MemcachedKeyLengthError Root Cause
Key length is > 250

Easily repeatable; I don't know the precise max page name length design.

**Comment by philipn** [comment]
This issue was moved to localwiki/localwiki-backend-server#7
