### ISSUE TITLE
Visiting the _create bare URL generates an error

### ISSUE THREAD

**Issue by vielmetti** [localwiki/localwiki#718]
Repeat at http://localwiki.net/ann-arbor/_create

First spotted at 

https://app.getsentry.com/localwikiorg/localwiki/?url=http://localwiki.net/alamance/_create

Error message reads:

pages.views in get_redirect_url
AttributeError: 'NoneType' object has no attribute 'strip'

The code reads in pages/views.py

        if not pagename.strip():
            # No page name provided, so let's return a useful error message.
            messages.add_message(self.request, messages.SUCCESS,
                _('You must provide a page name when creating a page.'))

but that useful error message does not in fact get displayed, so I think we need a different test.

**Comment by philipn** [comment]
This issue was moved to localwiki/localwiki-backend-server#6
