### ISSUE TITLE
Tag each page with Date / Time

### ISSUE THREAD

**Issue by cgorringe** [localwiki/localwiki#720]
I would like to see a new feature where every page may be tagged with a date/time stamp.  Similar to tagging each page with locations on a map, except for time!

Once you have this, we can then implement more features such as a Calendar widget that could show all pages with a given Tag on a calendar.

Or how about a summary page, where you can list all pages of a given Tag, sorted in date time order (with optional date/time displayed next to the page title)

Or a List of Events showing the next X events from now (each event having it's own page), which are automatically removed once the event has passed.  Each Event page would have the same Tag, so you can list all events with the given tag.

I'd REALLY like to see a Calendar widget feature for our city's front page!

**Comment by philipn** [comment]
Integrating into #516
