### ISSUE TITLE
In default editor, copy-and-pasting internal links temporarily gives them external link styling

### ISSUE THREAD

**Issue by brittag** [localwiki/localwiki#726]
While editing in the WYSIWYG editor, if I make a typical internal wikilink (select text, make it link to a page on that wiki) for a word in a sentence, then copy and paste that sentence, the pasted link has the tiny arrow icon at left that indicates an external link. If I select that word and set up the link again, the icon goes away, and it also goes away when I save the page.

This isn't a major functionality problem or anything, it's just a little bit confusing/unexpected while editing. :)

**Comment by philipn** [comment]
This issue was moved to localwiki/localwiki-backend-server#5
