### ISSUE TITLE
Newly-written image captions sometimes disappear after clicking something else in editor

### ISSUE THREAD

**Issue by brittag** [localwiki/localwiki#727]
Sometimes I've added a caption to a photo and found that the caption disappeared when I clicked something else, and usually I've just rewritten the caption, but here's an effort at figuring out how to reproduce the problem instead. :) This is using the default/visual editor.

1. I have a h3 with a paragraph after it, and I add a new line before the paragraph (it's a normal/paragraph mode line).
2. I insert a photo in this new line space.
3. I double click the photo and select right alignment.
4. I click the photo, select "Add a caption", delete it, and write a new caption.
5. Then I click somewhere else on the page, and the caption disappears.

**Comment by philipn** [comment]
This issue was moved to localwiki/localwiki-backend-server#4
