### ISSUE TITLE
Rename "revert" to "restore this version"

### ISSUE THREAD

**Issue by brittag** [localwiki/localwiki#728]
Looking at an [article history page like this one](https://localwiki.org/islavista/Isla_Vista_Screen_Printing/_history/), at first glance I wasn't sure whether the "revert" buttons meant "remove this edit and reinstate the older version" or "remove newer edits and reinstate this version".

I guessed correctly that it was the second one since the newest edit didn't have a "revert" button, but this felt a little odd since I'm accustomed to Wikipedia, where the "undo" buttons next to each edit (when looking at an article history) mean "remove this edit".

I think just renaming this button to "revert to this version" or similar could be helpful.

**Comment by philipn** [comment]
Thanks!  Just pushed a change to the UI to fix this.
