### ISSUE TITLE
Region dashboard has confusing info for number of users and "Users registered over time"

### ISSUE THREAD

**Issue by brittag** [localwiki/localwiki#729]
On region dashboards [like this one](https://localwiki.org/_tools/dashboard/islavista), it looks like the user count (in the top-of-page summary and bottom-of-page chart) is LocalWiki-wide instead of region-specific, unlike the other types of information on that page. Not a big problem, but slightly odd - maybe should have a label indicating the difference?

**Comment by mwanner2** [comment]
I think it's an important issue.  Not something we need yesterday, but something that should be addressed.

**Comment by philipn** [comment]
Thanks! Should now be fixed.
