### ISSUE TITLE
Received a proxy error upon trying to save an edit

### ISSUE THREAD

**Issue by brittag** [localwiki/localwiki#730]
When I tried saving [the content in this edit](https://localwiki.org/islavista/Coal_Oil_Point/_history/11) a few minutes ago, on my first try I got an error message:

> Proxy Error

> The proxy server received an invalid response from an upstream server.
> The proxy server could not handle the request POST /islavista/Coal_Oil_Point/_edit.

> Reason: Error reading from remote server

> Apache/2.2.22 (Ubuntu) Server at localwiki.org Port 443

Luckily when I went back in my browser, my content was still there in the editing interface, and clicking "save" was successful the second time.

**Comment by philipn** [comment]
Unclear if this was just a random blip, so I'm closing this out for now.  Please re-open if you see this again!

**Comment by brittag** [comment]
I saw this again tonight, on my first try when saving [the content in this edit](https://localwiki.org/sf/25th_Street_Telco_Building/_history/27). Like before, the second try went fine.
