### ISSUE TITLE
Received a server error when saving a map edit

### ISSUE THREAD

**Issue by brittag** [localwiki/localwiki#731]
When trying to fix [this map](https://localwiki.org/sf/map/Bryant_Street_MUNI_building/_history/), I got an error when I removed the original point and tried making the rectangle:

> Server error

> Looks like something went wrong and we're unable to display the page you requested.

> Please try again in a few minutes.

That happened a few times when trying the same thing.

It worked after I tried removing the point, attempting to save, putting the point in the right spot, saving, and then removing the point and making a rectangle and saving again. That may have been a coincidence of some kind since I don't really know how that would have been different. :)

**Comment by philipn** [comment]
Unclear if this was just a random blip, so I'm closing this out for now.  Please re-open if you see this again!
