### ISSUE TITLE
Diffs with changed image size, links, or other non-text content are confusing to interpret at first

### ISSUE THREAD

**Issue by brittag** [localwiki/localwiki#732]
On diff comparison pages, text removals and additions easy to see because they're highlighted in red/green, but some other kinds of changes are not highlighted with a color when looking at the diff (such as changes to image size or additions of links), so it's easy to miss those changes when looking quickly. (I did accidentally figure out that hovering gets a yellow popup with change info, and a while later I noticed the "review changes" button, but at a glance I don't know if I need to click the "review changes" button to find more changes.)

For example, looking at [this diff](https://localwiki.org/sf/Englander_House/_history/2014-12-15%2006:27:23.052226...), the image size has changed, and there are two new links in the first sentence, but that's not highlighted when looking at a glance; it can seem like the only change is that the "See also" content has been added.

I don't know the best way to fix this, and you might already have something different in mind, but it could be nice to put a yellow border around non-text changes, to hint to the viewer that they should hover over the yellow areas if they want to learn more via yellow popups.

**Comment by philipn** [comment]
This issue was moved to localwiki/localwiki-backend-server#3
