### ISSUE TITLE
Lines on maps are thin

### ISSUE THREAD

**Issue by hampelm** [localwiki/localwiki#733]
I was checking out [Postcard Row](https://localwiki.org/sf/Postcard_Row). A slightly higher-contrast color or thicker line could help the map element stand out more -- it really blends in:  

![screen shot 2014-12-16 at 6 01 30 pm](https://cloud.githubusercontent.com/assets/86435/5463793/aa4230d4-854d-11e4-8def-a0d073f769dc.png)

Diviz, which is larger, stands out a bit more: 

![screen shot 2014-12-16 at 6 04 03 pm](https://cloud.githubusercontent.com/assets/86435/5463810/f1c6ece2-854d-11e4-9076-742cc2c24db4.png)

**Comment by philipn** [comment]
This issue was moved to localwiki/localwiki-backend-server#2
