### ISSUE TITLE
case-insensitive tags

### ISSUE THREAD

**Issue by cgorringe** [localwiki/localwiki#734]
Currently when creating or using tags, if you have 2 tags with different capitalization, they are treated as different tags.  e.g. "Downtown" and "downtown".

I would like to continue allowing different capitalization when creating / using tags on a page, but when referencing them, such as when creating a list of pages of a particular tag, would like to see all pages listed with every variation of the tag in a case-insensitive manner.

**Comment by cgorringe** [comment]
nevermind, looks like it already works like this...

**Comment by philipn** [comment]
Can you paste a link to where you see this happening? Behavior should be case-insensitive but case-preserving as you describe.

**Comment by cgorringe** [comment]
I thought I saw this happening before, but when I just tried it, it appears to work OK, and I forget where I thought I saw this happening.  Will update this if I see it again, but likely I was just mistaken.
