### ISSUE TITLE
More button on News Feed loads same stuff that was already there again

### ISSUE THREAD

**Issue by douglaswth** [localwiki/localwiki#735]

**Comment by philipn** [comment]
Thanks, @douglaswth! Could you give an example? The "more" button should show a page group (again) if there's more changes under that page, but shouldn't actually show the /same/ changes. Not sure if that makes sense.  The alternative, with our current changes-grouped-by-page design, would be to update the list of changes under hte page title, which wouldn't look intuitive, I don't think?

**Comment by douglaswth** [comment]
This is happening when I go to https://localwiki.org/ while logged in:

![image](https://cloud.githubusercontent.com/assets/77890/5822331/fce41636-a087-11e4-8c26-aac96f3de40d.png)

I'll scroll to the bottom:

![image](https://cloud.githubusercontent.com/assets/77890/5822342/172eb866-a088-11e4-9b5f-499a31bed36c.png)

And then click More and the next items are the same as the ones at the top of the page:

![image](https://cloud.githubusercontent.com/assets/77890/5822358/37044ca0-a088-11e4-8d27-bd7c5865e448.png)

And if I scroll to the bottom the last items are the same ones as were at the bottom before; clicking More again will just repeat the same stuff.

**Comment by philipn** [comment]
Ah, got it! I can reproduce it now. I wasn't see it on the individual region's activity pages (https://localwiki.org/sf/_activity) or on the global activity feed page (https://localwiki.org/_activity)

**Comment by philipn** [comment]
Thanks! Should now be fixed.
