### ISSUE TITLE
New visited link style in Activity view looks "greyed out"/disabled

### ISSUE THREAD

**Issue by brittag** [localwiki/localwiki#739]
Looking at an Activity page (such as https://localwiki.org/_activity), the new visited-link style made me wonder at first glance whether those links were disabled in some way instead of just being visited, since it looks sort of "greyed out", as in "this isn't clickable anymore".

A bunch of other aspects of the new styling are nice though!

**Comment by philipn** [comment]
Thanks! Should be fixed now.
