### ISSUE TITLE
Explore Nearby Regions list on front page not up-to-date

### ISSUE THREAD

**Issue by cgorringe** [localwiki/localwiki#740]
I’ve noticed that in every localwiki site in the SF Bay Area (e.g. Oakland, San Francisco, Fremont, etc) none will show Hayward in the Explore Nearby Regions section of the Front Page, even though for example on the Oakland front page, Hayward is closer to Oakland than Fremont is.  Also the Berkeley page will show Fremont and Sonoma Valley, but not Oakland, which obviously should be listed there.

I'm guessing that this section must be manually created, though can't find where the user can edit it.  It would be great if the Nearby Regions list would be automatically generated based on distance of it's N-closest regions and kept somewhat up-to-date.

**Comment by philipn** [comment]
Thanks!  Should now be fixed.
