### ISSUE TITLE
On Explore Regions page, some regions aren't properly linked

### ISSUE THREAD

**Issue by brittag** [localwiki/localwiki#744]
If you go to https://localwiki.org/regions and scroll down a bit, some of the no-preview-photo regions don't link to their appropriate region pages - they link to ```<a href="/">``` instead. For example: Canton, MI; Boise; Ithaca. This happens for me in both Safari and Chrome on OS X.

**Comment by philipn** [comment]
I believe this has now been fixed in https://github.com/localwiki/localwiki-backend-server/commit/016d04325a87bbf8f2a18825a8321550b4546108, and with a manual cache clearing.  Please re-open if you see this again!
