### ISSUE TITLE
What happened to Template Pages?

### ISSUE THREAD

**Issue by cgorringe** [localwiki/localwiki#745]
When clicking on "Add a New Page", there use to be a list of Template pages that we could select from.  Where did they go?  This was a very useful feature!

**Comment by philipn** [comment]
This was removed for now. It was extremely confusing on a number of levels, and was the #1 confusing thing for new editors.

**Comment by cgorringe** [comment]
Oh that's too bad.  I hope we can reintroduce it someday.  I find it much harder now without template pages to create those tables with shaded cells.  I need to look at the source of an existing page and copy and paste into a new page.  Perhaps an alternative would be to allow a user to create a duplicate/copy of an existing page when creating a new page, instead of always starting with an empty page.

**Comment by philipn** [comment]
We'll revisit this once the (eventual) `infobox` functionality is finished.

**Comment by pm5** [comment]
We are currently modifying LocalWiki for our project [here](https://github.com/lowiki-org/localwiki-backend-server).  Our community really wants to use templates, so we are adding a MediaWiki-style template feature that allows editor to insert a template using the `{{template-name}}` syntax.  Not sure how this will turn out, but we'd be happy to know if there are any suggestions and ideas from upstream.

**Comment by philipn** [comment]
@pm5 The old templates feature was not like the MediaWiki-style template (transclusion): it was more just a set of 'preset' pages, akin to what you'd see when you e.g. open a word processor and see the 'template document' types.

Our focus has always been on ease of use.  For the old templates system, it was confusing for a few reasons.

One reason is that people instinctually wanted to create a page using a template when the function was presented to them, and then wanted to make a new kind of template for every kind of page.  But then this left people feeling like, if there wasn't a template for the kind-of-thing-this-page-is, then the page shouldn't be created.  Or that the template should exist first, but the user typically didn't know how to create the template page.  Even when there was a template page available, this meant that people tended to want to write lots of information into preset table cells and headings (or, if they weren't present, they felt like they "weren't supposed to" write things a particular way).  So in this one respect, we found it limited participation and stifled writing.  And for the major argument for these templates -- normalization -- we found that regular editors could help polish-up pages after they were created, or e.g. someone could write a script using the API.

**Comment by pm5** [comment]
@philipn as it goes our project has been building some more features on top of the MediaWiki-style template system we've added.  We plan to implement:
- Some form of bindings between tags and templates.  For example, when editors add a "restaurant" tag to a page, the template tag of "Restaurant" will be automatically inserted at the beginning of the page.
- Import CSV to bulk create pages using one template, filling the template fields with the data in CSV fields.
- Some more structured input UI to help creating template pages from mobile devices.

Not sure if these are suitable for localwiki.org.  If there is interest to merge our work back to upstream we'd be happy to prepare a pull request for it.

Our template-related changes will be in [this branch](https://github.com/lowiki-org/localwiki-backend-server/tree/18-wikitext) if anyone is interested.

**Comment by nicogreenarry** [comment]
Instead of templates for whole page-types, has localwiki ever tried using a library of components that could be inserted in the page? Maybe that could just mean extending the "Insert object" item in the WYSIWYG. New editors wouldn't feel that they needed a template to create a type of page, but it would still be easy for them to easily add a table with shaded cells, for example.
