### ISSUE TITLE
Changes to not-logged-in editing behavior

### ISSUE THREAD

**Issue by philipn** [localwiki/localwiki#747]
Explore something like:
- Anyone can press "Edit", make changes, and press "Save," whether logged in or not.
- After the save goes through, they're prompted to either log in or create an account.
- The edit is then actually saved and they're redirected back to the saved-page screen after logging in or creating an account.

& test to see if engagement is roughly the same with this versus the status quo of not-authenticated editing.

**Comment by cgorringe** [comment]
I've edited pages many times before assuming I was logged in, but was actually not by accident, so anything that can help to let me log in after the edit and attribute the change to my username would really help!

**Comment by philipn** [comment]
It seems like folks don't much like the IP-based attribution for non-authenticated edits. I'm not sure what changes are required for the above workflow, but even simply requiring all edits to be made by logged-in users (e.g. redirecting to the login / sign up page on editable actions) would be a step in the right direction.
