### ISSUE TITLE
Logged-out view is showing outdated version of articles

### ISSUE THREAD

**Issue by brittag** [localwiki/localwiki#770]
Similar to issue #769, https://localwiki.org/islavista/Lost_Murals_of_Isla_Vista is showing an old version (without the additions on February 23) when logged out.

https://localwiki.org/tiburon/Angel_Island is also showing an old version when logged out (without the changes on Feb 12 and 14).

**Comment by philipn** [comment]
Looks like this is the same problem as before, and should now be fixed (after editing).  I've added the missing step to our deployment script, so it shouldn't happen again (hopefully!)

**Comment by brittag** [comment]
Yay thanks! 🎉
