### ISSUE TITLE
Question on API use

### ISSUE THREAD

**Issue by jayzam** [localwiki/localwiki#785]
Is there anyway to link the the FILES api to the PAGES API?  I want to get the files associated with a page.

Jay

**Comment by philipn** [comment]
I think the way to do this would be to filter the files endpoint according to the page's `slug`. So if the page was named "My Page", you would filter files according to `slug=my%20page`.

Check out the documentation on how filtering works, as this may be the missing piece for you

**Comment by philipn** [comment]
Closing this, as the question was (hopefully!) answered.
