### ISSUE TITLE
Localwiki interface translation updates 

### ISSUE THREAD

**Issue by charlesc** [localwiki/localwiki#786]
We are going to host a workshop and use Localwiki in early Aug. 
I wonder if we can translate https://www.transifex.com/localwiki/localwiki/language/zh/ to 100% in 2 weeks, is it possible for you to push out translation updates into Localwiki.org by the end of July?

**Comment by philipn** [comment]
Hey Charles-

Yes, that shouldn't be a problem. Just comment back here when the translation is complete and we will push out an update.

**Comment by charlesc** [comment]
Thank you Philip,  will be back soon.

**Comment by charlesc** [comment]
100% translated! need review. Please assign my account at Transifex as a moderator. Thank you!

**Comment by charlesc** [comment]
It's almost done. I will review all the strings by this weekend.

**Comment by charlesc** [comment]
Hi @philipn ，100% reviewed now. Please update so we can try it online. Thank you!!

**Comment by charlesc** [comment]
Hi @philipn , when could we see the language update at locawiki.org? or a test/dev server?  (sorry for pushing you)

**Comment by philipn** [comment]
Can someone push this out? Instructions are here:

https://localwiki.org/dev/i18n

**Comment by charlesc** [comment]
Oh... I have no idea. Please help by tomorrow?

**Comment by philipn** [comment]
Okay, the new strings should be available at:

https://zh.localwiki.org

Please let me know if you'd like me to convert the existing Taiwanese regions to `zh`.  This can be done by any region admin in the "settings" area, under "Default language."

**Comment by charlesc** [comment]
Thank you @philipn !!
