### ISSUE TITLE
Reviving old account doesn't seem to readily work

### ISSUE THREAD

**Issue by darachm** [localwiki/localwiki#793]
I recently tried to recover my account on DavisWiki after probably about 9 years of domancy (I remembered Steve Inness and wanted to post on his memorial page). I tried to do the email recovery and entered in my email, did that twice, and it's been ~20 minutes and I haven't received any emails (nothing in spam as far as I can tell, I don't know of any filtering mechanism that would block it). It's a gmail account.

If anyone knows, does DavisWiki email recovery work, ie is that still active? Would a email database from 9 years ago be linked up with an accounts database properly? If not, could I recover it manually? Anyway for me to troubleshoot it on my end?

Sorry for the trouble. I did help with the DavisWiki fundraiser a little bit, back in the day, btw : )

**Comment by JadonKY** [comment]
Me As Well! I just tried to log in and had issues. Now I know the password was correct but nothing worked. so I tried to reset the password but no email was sent. This happened multiple times. 

local wiki account:  CaymanianContributer

**Comment by philipn** [comment]
@JadonKY @darachm This issue should now (finally) be fixed.

If you try and reset your password now, you should get an email. It may appear in your spam folder so please check there as well. Previously, most email hosts were not even delivering the email at all.

It looks like after changing one of our IP addresses we were back on the default PBL spamhaus blacklists. I requested a removal and it appears to be working for me now (for my personal gmail account).

**Comment by JadonKY** [comment]
Hi Philip,

Thank you so much for the update. I will try to log in again.

Regards,
Jadon

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by darachm** [comment]
Hey it works. Password reset email got flagged spam by gmail. But works.

Thanks Philip.
