### ISSUE TITLE
Website is not clear about status!

### ISSUE THREAD

**Issue by zblace** [localwiki/localwiki#794]
It seems that development stalled and it is unfortunate as it seems like it had intense few years, but now it is not actively developed here - no? Website is not clear about status!

**Comment by philipn** [comment]
LocalWiki is actively managed/maintained but I personally haven't done any development in a while. Pull requests are accepted as is help in other ways.

**Comment by zblace** [comment]
@philipn are you the lead developer? anyone else able to develop or at least document features?
I like the use of maps, but it is hard to understand what is possible to edit with so little documentation.

**Comment by InnisfreeM** [comment]
I can help a little with the mapping aspects. The maps are based on open
street map, so if you aren't getting the features you need, you can edit
the basemaps themselves to improve what shows up.
https://www.openstreetmap.org/

The thing that concerns me the most is that the wiki doesn't show up well
on smartphones. It would be great to do some work to develop a more
responsive layout. But I'm not a developer so until I find someone with
those skills I will have to not complain!

Innisfree

**Comment by philipn** [comment]
There is lots of documentation. Please see

https://localwiki.org/main

E.g.
https://localwiki.org/main/Mapping

**Comment by zblace** [comment]
> I can help a little with the mapping aspects. The maps are based on open street map, so if you aren't getting the features you need, you can edit the basemaps themselves to improve what shows up. https://www.openstreetmap.org/

OK - I will look into this and likely need advice, but for the moment I want to do few simple things, like changing the default rendering or display size of maps on pages that are mapped on, but this is not a documented option. At least not on 
https://localwiki.org/main/Mapping @philipn
